---
- name: Create Azure VM with Public IP (Standard SKU)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: myResourceGroup
    location: francecentral
    vnet_name: myVNet
    subnet_name: mySubnet
    public_ip_name: myPublicIP
    nsg_name: myNSG
    nic_name: myNIC
    vm_name: myVM
    admin_username: azureuser
    # NOTE: En prod, utilise Ansible Vault.
    admin_password: YourSecurePassword123!

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        virtual_network: "{{ vnet_name }}"
        address_prefix: "10.0.1.0/24"

    - name: Create Public IP (Standard SKU)
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        name: "{{ public_ip_name }}"
        location: "{{ location }}"
        sku: Standard            # Fix: Required to bypass Basic quota limit
        allocation_method: Static # Fix: Required for Standard SKU

    - name: Create Network Security Group (NSG)
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nsg_name }}"
        location: "{{ location }}"
        rules:
          - name: AllowSSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create NIC (Link IP & NSG)
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_address_name: "{{ public_ip_name }}" # Fix: Correct parameter name
        security_group: "{{ nsg_name }}"               # Fix: Attach NSG for SSH access
        location: "{{ location }}"

    - name: Create Virtual Machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_B1s
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ nic_name }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '8-stream'
          version: latest
        location: "{{ location }}"

    - name: Output Public IP
      debug:
        msg: "Public IP created: {{ public_ip_name }} (Check Azure Portal for exact IP as it is Static Standard)"