---
- name: Créer une VM Azure avec Public IP (Corrected)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    resource_group_name: myResourceGroup
    location: francecentral
    vnet_name: myVNet
    subnet_name: mySubnet
    public_ip_name: myPublicIP
    nic_name: myNic
    vm_name: myVM
    admin_username: azureuser
    admin_password: YourSecurePassword123!

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "10.0.0.0/16"
        location: "{{ location }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: "{{ subnet_name }}"
        virtual_network: "{{ vnet_name }}"
        address_prefix: "10.0.1.0/24"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
        location: "{{ location }}"

    - name: Create NIC with Public IP
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_address_name: "{{ public_ip_name }}"
        location: "{{ location }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_B1s
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ nic_name }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '8-stream'
          version: latest
        location: "{{ location }}"